language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
branches:
  only:
  - master
  - develop
before_install:
  - sudo apt-get install swig
install:
  - pip install torch==1.5.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
  - pip install -e .["dev"]
script:
  - make lint
  - make test
